module.exports = Object.freeze({
  url: "https://music.apple.com/",
  name: "Apple Music",
  productName: "Apple Music",
  repoName: "apple-music-aaha",
  versionLabel: "v0.9.3",
  appId: "com.adamandhisagents.applemusic",
  desktopName: "com.adamandhisagents.applemusic.desktop",
  wmClass: "com.adamandhisagents.applemusic",
  executableName: "apple-music-aaha",
  executable: "apple-music-aaha",
  iconName: "apple-music-aaha",
  profileName: "Apple Music",
  legacyProfileNames: [],
  compatibilityDesktopIds: [],
  comment: "Apple Music web player",
  category: "AudioVideo;Audio;Player;",
  keywords: "music;audio;streaming;apple;",
  width: 1440,
  height: 900,
  minWidth: 800,
  minHeight: 600,
  openExternalInBrowser: true,
  allowedHostSuffixes: ["apple.com", "icloud.com"],
  allowedPermissions: ["mediaKeySystem"],
  widevineUpdateIntervalDays: 30,
  blockedHostSuffixes: [
    "1e100.net",
    "doubleclick.net",
    "google.com",
    "google-analytics.com",
    "googleapis.com",
    "googleusercontent.com",
    "googlesyndication.com",
    "googletagmanager.com",
    "gstatic.com",
    "youtu.be",
    "youtube.com"
  ],
  forceX11: false,
  disableHardening: false
});
